apiVersion: v1
kind: Template
metadata:
  name: package-extract-buildconfig
  annotations:
    description: This is Thoth Core - Package Extract BuildConfig
    openshift.io/display-name: "Thoth: Package Extract BuildConfig"
    version: 0.2.0
    tags: poc,thoth,ai-stacks,package-extract
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth
      Package Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: package-extract-buildconfig
    app: thoth
    component: package-extract

objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: package-extract-base
    labels:
      app: thoth
      component: package-extract
  spec:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 2
        memory: 1024Mi
    output:
      to:
        kind: ImageStreamTag
        name: "package-extract-base:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: "${GITHUB_URL}"
        ref: "${GITHUB_REF}"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile-base.fedora
        from:
          kind: DockerImage
          name: fedora:27
        imageOptimizationPolicy: SkipLayers
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: package-extract-job
    labels:
      app: thoth
      component: package-extract
  spec:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 2
        memory: 1024Mi
    output:
      to:
        kind: ImageStreamTag
        name: "package-extract-job:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: "${GITHUB_URL}"
        ref: "${GITHUB_REF}"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: ImageStreamTag
          name: "package-extract-base:${IMAGE_STREAM_TAG}"
        imageOptimizationPolicy: SkipLayers
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

parameters:
- description: Name of the github repository
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/package-extract'

- description: Git reference to be used
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: |-
    Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
